version: '3.9'

services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: chatroomDb
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/db:/var/lib/mongodb
